version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cdss-comprehensive-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cdss-comprehensive-frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
